import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve, normalize } from 'node:path';
import {
  validateHandover,
  createResult
} from '../lib/handover_schema.mjs';

function readStdin() {
  return new Promise((resolvePromise, rejectPromise) => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', chunk => {
      data += chunk;
    });
    process.stdin.on('end', () => {
      resolvePromise(data);
    });
    process.stdin.on('error', err => {
      rejectPromise(err);
    });
  });
}

async function getHandoverData() {
  const arg = process.argv.slice(2).find(a => a.startsWith('--handover='));
  if (arg) {
    const raw = arg.slice('--handover='.length);
    return JSON.parse(raw);
  }
  const stdinData = await readStdin();
  if (stdinData.trim().length > 0) {
    return JSON.parse(stdinData.trim());
  }
  throw new Error('No Handover Package provided to Recorder Worker');
}

const RECORD_PATH_REGEX = /^\.agents\/records\/record-\d{3,}-[\w-]+\.md$/;

function validateTargetPath(targetPath) {
  const normalized = normalize(targetPath).replace(/\\/g, '/');

  if (!RECORD_PATH_REGEX.test(normalized)) {
    throw new Error(`Permission Denied: Target path "${targetPath}" is outside allowed record pattern: ^\\.agents\\/records\\/record-\\d{3,}-[\\w-]+\\.md$`);
  }

  const forbiddenPrefixes = [
    'active/',
    'data/',
    'deployment.json',
    'AGENTS.md',
    '.agents/rules/',
    '.agents/skills/',
    '.agents/workflows/',
    '.agents/agents/',
    '.agents/current-scope.json'
  ];

  for (const forbidden of forbiddenPrefixes) {
    if (normalized === forbidden || normalized.startsWith(forbidden)) {
      throw new Error(`Permission Denied: Target path "${targetPath}" violates protected path "${forbidden}"`);
    }
  }

  return normalized;
}

async function recordTask(handover, workerStartTime) {
  const cwd = process.cwd();
  const context = handover.context || {};
  const recordFileName = context.recordFileName || (handover.scope && handover.scope[0]);

  if (!recordFileName) {
    throw new Error('No record file name specified in handover scope or context.recordFileName');
  }

  const validatedRelativePath = validateTargetPath(recordFileName);
  const fullPath = resolve(cwd, validatedRelativePath);

  if (existsSync(fullPath) && !context.allowOverwrite) {
    throw new Error(`Safety Violation: Existing official record "${validatedRelativePath}" cannot be overwritten without explicit allowOverwrite.`);
  }

  const title = context.title || 'POSTING MAP Automated Execution Record';
  const recordId = context.recordId || validatedRelativePath.replace(/^\.agents\/records\//, '').replace(/\.md$/, '').toUpperCase();
  const contentBody = context.contentBody || 'Automated record entry generated by Recorder Worker.';

  const markdownContent = [
    `# ${title}`,
    '',
    `- **記録ID**: ${recordId}`,
    `- **作成日時**: ${new Date().toISOString()}`,
    `- **Worker PID**: ${process.pid}`,
    `- **Parent PID**: ${process.ppid}`,
    `- **ステータス**: PASS`,
    '',
    '---',
    '',
    '## 記録内容 (Observed Evidence)',
    '',
    contentBody,
    ''
  ].join('\n');

  writeFileSync(fullPath, markdownContent, 'utf8');

  const workerEndTime = Date.now();
  const durationMs = workerEndTime - workerStartTime;

  const result = createResult({
    taskId: handover.taskId,
    agent: 'recorder',
    status: 'PASS',
    summary: `Successfully recorded evidence to ${validatedRelativePath}`,
    details: {
      targetFile: validatedRelativePath,
      workerPid: process.pid,
      parentPid: process.ppid,
      workerStartTime: new Date(workerStartTime).toISOString(),
      workerEndTime: new Date(workerEndTime).toISOString(),
      bytesWritten: Buffer.byteLength(markdownContent, 'utf8')
    },
    issues: [],
    evidence: [
      `Wrote record file: ${validatedRelativePath} (${Buffer.byteLength(markdownContent, 'utf8')} bytes)`,
      'Target path validated against .agents/records/ whitelist regex.',
      'Protected paths verification passed with zero violations.'
    ],
    changedFiles: [validatedRelativePath],
    durationMs
  });

  return result;
}

async function main() {
  const workerStartTime = Date.now();
  try {
    const handover = await getHandoverData();
    const { valid, errors } = validateHandover(handover);
    if (!valid) {
      console.error(JSON.stringify({ error: 'Invalid Handover', details: errors }));
      process.exit(1);
    }
    if (handover.targetAgent !== 'recorder') {
      console.error(JSON.stringify({ error: `Recorder Worker received non-recorder targetAgent: ${handover.targetAgent}` }));
      process.exit(1);
    }

    const result = await recordTask(handover, workerStartTime);
    console.log(JSON.stringify(result, null, 2));
    process.exit(0);
  } catch (err) {
    console.error(JSON.stringify({
      error: err.message,
      workerPid: process.pid,
      stack: err.stack
    }));
    process.exit(1);
  }
}

main();
